_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
architecture:
    value: YOLOv11
batch_size:
    value: 8
dataset:
    value: group_bees_2024
epochs:
    value: 100
img_size:
    value: 640
learning_rate:
    value: 0.01
